apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webrust.fullname" . }}-db
  labels:
    {{- include "webrust.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  DATABASE_URI: {{ printf "postgres://%s:%s@%s-postgres:%v/%s" .Values.database.user .Values.database.password (include "webrust.fullname" .) .Values.database.port .Values.database.name | quote }}
