{{- if .Values.database.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "webrust.fullname" . }}-postgres
  labels:
    {{- include "webrust.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.persistence.size | quote }}
  {{- if .Values.database.persistence.storageClassName }}
  storageClassName: {{ .Values.database.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
