apiversion: 1

# Configure Prometheus datasource automatically.
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    is_default: true
    editable: false
    jsonData:
      httpMethod: GET
